tmdb:
  api:
    key: 6630d7c54c802d0a954063c6b4c0e163

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movieapp_db?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mhrcfnc5@Family

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
